# Generated by Django 5.0.4 on 2024-05-23 17:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCourses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendingattempt',
            name='send_datetime',
        ),
        migrations.AddField(
            model_name='sendingattempt',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyCourses.client', verbose_name='клиент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendingattempt',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время отправки'),
        ),
        migrations.AlterField(
            model_name='sendingattempt',
            name='server_response',
            field=models.TextField(blank=True, null=True, verbose_name='ответ сервера'),
        ),
        migrations.AlterField(
            model_name='sendingattempt',
            name='status',
            field=models.CharField(max_length=100, verbose_name='статус'),
        ),
        migrations.CreateModel(
            name='MailingSrv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время начала рассылки')),
                ('next', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время следующей рассылки')),
                ('finish', models.DateTimeField(verbose_name='время завершения рассылки')),
                ('status', models.CharField(choices=[('создана', 'создана'), ('запущена', 'запущена'), ('завершена', 'завершена')], default='создана', max_length=100, verbose_name='статус рассылки')),
                ('frequency', models.CharField(choices=[('один раз', 'один раз'), ('раз в день', 'раз в день'), ('раз в неделю', 'раз в неделю'), ('раз в месяц', 'раз в месяц')], max_length=50, verbose_name='периодичность рассылки')),
                ('is_activated', models.BooleanField(default=True, verbose_name='метка активности')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('recipients', models.ManyToManyField(to='MyCourses.client', verbose_name='получатели рассылки')),
            ],
        ),
        migrations.AlterField(
            model_name='sendingattempt',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyCourses.mailingsrv', verbose_name='рассылка'),
        ),
    ]
