# Generated by Django 5.0.4 on 2024-05-30 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCourses', '0003_remove_sendingattempt_send_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsrv',
            name='mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyCourses.message', verbose_name='письмо'),
        ),
    ]
